// --- PREGUNTAS DE PRUEBA ---
const preguntas = [
 {"texto": "9 de cada 10 Startup desaparecen en 3 años por falta de clientes.", "respuesta": true,
     "explicacion": "."},
    {"texto": "9 de cada 10 Startup desaparecen en 3 años por problemas entre los socios.", "respuesta": false,
     "explicacion": ". Aunque los conflictos entre socios son frecuentes, el motivo más común de cierre es la falta de clientes o mercado."},
    {"texto": "A partir de la información que proporciona la pirámide de Maslow se puede decidir si hay un espacio para posicionar un producto en un mercado determinado.", "respuesta": false,
     "explicacion": ". La pirámide de Maslow sirve para entender motivaciones humanas, no para decidir estrategias de posicionamiento de mercado."},
    {"texto": "Amortización es la distribución de gasto en un periodo determinado, de un valor duradero.", "respuesta": true,
     "explicacion": "Es el proceso de repartir el coste de un bien duradero a lo largo del tiempo, como una máquina o equipo."},
    {"texto": "Bienes de convivencia de emergencia son los que se compran sin ningún tipo de planificación o investigación y están disponibles en lugares estratégicos para que el consumidor se fije y los compre sin haberlo planificado.", "respuesta": false,
     "explicacion": ". Estás describiendo bienes de conveniencia o impulso, no de conveniencia o emergencia."},
    {"texto": "'Bootstrapping' = financiarse con recursos propios.", "respuesta": true,
     "explicacion": ". El término bootstrapping significa empezar un negocio sin inversión externa, usando tus propios medios."},
    {"texto": "Conocer la política de fidelización de clientes de mis competidores forma parte del benchmarking.", "respuesta": true,
     "explicacion": ". Benchmarking implica analizar buenas prácticas de la competencia, incluida su fidelización de clientes."},
    {"texto": "Consumidor es aquel que compra un producto.", "respuesta": false,
     "explicacion": ". Ojo, aquí confunden comprador con consumidor: el comprador puede adquirirlo, pero el consumidor es quien lo usa."},
    {"texto": "Cuando el modelo económico se entiende y tiene sentido para el cliente, es un buen momento para dejar de pivotar.", "respuesta": true,
     "explicacion": ". Pivotar se detiene cuando el modelo funciona y el cliente entiende el valor que se le ofrece."},
    {"texto": "Cuando hay una oportunidad de negocio que nadie ha desarrollado todavía hablamos de mercado en crecimiento.", "respuesta": false,
     "explicacion": ". Ojo, una oportunidad sin explotar puede estar en un mercado nuevo o inexistente, no necesariamente en crecimiento."},
    {"texto": "Cuando la hoja de ruta de ventas está validada y dispongo de pedidos reiterativos, es un buen momento para dejar de pivotar.", "respuesta": true,
     "explicacion": ". Si ya tienes clientes constantes y validación de ventas, se deja de pivotar."},
    {"texto": "Cuando un nuevo socio es amigo o familiar, es mucho más fácil, porque no es necesario poner normas o cláusulas contractuales por escrito.", "respuesta": false,
     "explicacion": ". Ojo, este es un error muy típico: con amigos o familia hay que dejarlo por escrito igual o más aún."},
    {"texto": "Cuando ya tengo un PMV que me ayuda a mejorar el modelo de negocio, es un buen momento para dejar de pivotar.", "respuesta": true,
     "explicacion": ". El PMV sirve para validar hipótesis; si ya te da feedback real, puedes avanzar sin más pivotes."},
    {"texto": "De los pilares de la persuasión, Ethos apela a la credibilidad.", "respuesta": true,
     "explicacion": ". Ethos se basa en la autoridad y credibilidad del emisor. Ojo, no confundir con Pathos o Logos."},
    {"texto": "De los pilares de la persuasión, Pathos apela a la razón.", "respuesta": false,
     "explicacion": ". Pathos apela a las emociones; el que apela a la razón es Logos."},
    {"texto": "Del márqueting mix, la distribución es el único instrumento que proporciona ingresos.", "respuesta": false,
     "explicacion": ". Ojo, el que realmente genera ingresos es el precio; los demás son costes o estrategias."},
    {"texto": "Demanda se define como la cantidad de bienes o servicios que los productores están dispuestos a vender a un precio dado en un momento determinado.", "respuesta": false,
     "explicacion": ". Esa definición es de oferta; demanda es lo que los consumidores están dispuestos a comprar."},
    {"texto": "Después de tener una idea, en las startups, lo más importante es validar si hay clientes interesados.", "respuesta": true,
     "explicacion": ". Ojo, mucha gente se lanza a fabricar sin validar; lo primero es comprobar si hay mercado real."},
    {"texto": "Dirigir es influir en las personas que forman la empresa para que hagan las tareas necesarias para alcanzar los objetivos marcados.", "respuesta": true,
     "explicacion": ". Dirigir es guiar e influir, no simplemente mandar."},
    {"texto": "Dropbox es un buen ejemplo de crowdfunding (PMV).", "respuesta": false,
     "explicacion": ". Dropbox usó un video demo (PMV tipo ‘Mago de Oz’), no una campaña de crowdfunding."},
    {"texto": "Eficacia es conseguir el objetivo propuesto.", "respuesta": true,
     "explicacion": ". Eficacia = lograr el resultado; eficiencia = lograrlo usando los mínimos recursos."},
    {"texto": "EFQM es una herramienta integral de calidad que tienen como objetivo ayudar a las organizaciones a conocerse mejor a sí mismas, a realizar un análisis objetivo, riguroso y estructurado de su funcionamiento y, en consecuencia, a mejorar su gestión.", "respuesta": true,
     "explicacion": ". EFQM es un modelo europeo de excelencia empresarial basado en la mejora continua."},
    {"texto": "El 50% de los clientes insatisfechos nunca se quejan.", "respuesta": true,
     "explicacion": ". Ojo, esto es clave: muchos clientes descontentos no se quejan, simplemente se van."},
    {"texto": "El análisis del mercado permitirá detectar oportunidades de negocio para la empresa y valorar la posibilidad de afrontar con las estrategias adecuadas.", "respuesta": true,
     "explicacion": ". Analizar el mercado sirve para detectar huecos y adaptar estrategias."},
    {"texto": "El aprendizaje validado es uno de los pilares de la metodología Lean Startup.", "respuesta": true,
     "explicacion": ". Lean Startup se basa en aprender rápido de los clientes a través de la validación de hipótesis."},
    {"texto": "El benchmarketing es una de las herramientas que utilizan las empresas para copiar a la competencia.", "respuesta": false,
     "explicacion": ". Ojo, benchmarking no es copiar, sino aprender y adaptar buenas prácticas."},
    {"texto": "El benchmarking es una de las herramientas que utilizan las empresas para poder consolidar su posición competitiva.", "respuesta": true,
     "explicacion": ". Sirve para comparar y mejorar procesos respecto a los líderes del sector."},
    {"texto": "El Beneficio Aportado por el Cliente = (Coste de Adquisición de clientes) * (% beneficio promedio).", "respuesta": false,
     "explicacion": ". Ojo, esto está mal planteado; el beneficio aportado no se calcula multiplicando costes, sino valorando margen y retención."},
    {"texto": "El business Model Canvas es un gráfico visual con elementos que describen propuestas de producto o de valor de la empresa, la infraestructura, los clientes y las finanzas.", "respuesta": true,
     "explicacion": ". El Canvas de Osterwalder muestra cómo se genera y entrega valor al cliente."},
    {"texto": "El Business Model Canvas fue enunciado inicialmente por Eric Ries.", "respuesta": false,
     "explicacion": ". Ojo, lo creó Alexander Osterwalder, no Eric Ries (que es el autor de Lean Startup)."},
    {"texto": "El canal de distribución corto definido por productor y consumidor.", "respuesta": false,
     "explicacion": ". Ojo, falta el verbo; la definición correcta es que el canal corto está formado solo por productor y consumidor."},
    {"texto": "El canal de venta es un elemento fundamental en la creación del modelo de negocio de una startup.", "respuesta": true,
     "explicacion": ". Elegir bien el canal de venta puede determinar la viabilidad del negocio."},
    {"texto": "El CANVAS es un gráfico visual de gestión estratégica que se usa para representar modelos de negocio.", "respuesta": true,
     "explicacion": ". Es una herramienta clave para visualizar el modelo global de una empresa."},
    {"texto": "El cargo de un director de la autoridad sobre sus trabajadores.", "respuesta": false,
     "explicacion": ". Tener cargo no implica tener autoridad moral o liderazgo efectivo."},
    {"texto": "El ciclo de aprendizaje de una Startup es construir, medir y aprender.", "respuesta": true,
     "explicacion": ". Es el núcleo del método Lean Startup: probar, medir y mejorar."},
    {"texto": "El coaching es sueldo emocional.", "respuesta": true,
     "explicacion": ". Se considera parte del salario emocional porque motiva y desarrolla al empleado."},
    {"texto": "El comprador no siempre es consumidor, pero el consumidor siempre el comprador de un producto.", "respuesta": false,
     "explicacion": ". Ojo, el consumidor no tiene por qué ser quien compra; puede usar un producto adquirido por otro."},
    {"texto": "El concepto de mercado puede ser abstracto.", "respuesta": false,
     "explicacion": ". El mercado siempre implica interacción entre oferta y demanda reales, no un concepto abstracto."},
    {"texto": "El confirming es un tipo de préstamo de poca cantidad destinado tanto para personas físicas como para la financiación de empresas y proyectos sociales.", "respuesta": false,
     "explicacion": ". El confirming es una herramienta financiera para gestionar pagos a proveedores, no un préstamo pequeño."},
    {"texto": "El consumidor busca un equilibrio entre el coste de adquisición y el beneficio que representa la compra del producto.", "respuesta": true,
     "explicacion": ". Los consumidores valoran la relación coste-beneficio al decidir comprar."},
    {"texto": "El contenido de un CRM está basado en los datos que el backoffice de un departamento comercial proporciona.", "respuesta": false,
     "explicacion": ". Ojo, el CRM centraliza datos de clientes de toda la empresa, no solo del backoffice comercial."},
    {"texto": "El contenido de una visita comercial debe ser igual en las visitas de ventas, sea cual sea el tipo de cliente al que visita.", "respuesta": false,
     "explicacion": ". Cada visita debe adaptarse al tipo de cliente, sector y necesidad."},
    {"texto": "El coste de oportunidad designa el coste de inversión de los recursos disponibles a costa de la mejor inversión alternativa disponible.", "respuesta": true,
     "explicacion": ". Es lo que dejas de ganar por elegir una opción frente a otra."},
    {"texto": "El crédito comercial es un tipo de financiación para empresas y emprendedores que consiste en el aplazamiento del pago de una compraventa.", "respuesta": true,
     "explicacion": ". Es una forma habitual de financiación entre empresas."},
    {"texto": "El CRM es una técnica publicitaria.", "respuesta": false,
     "explicacion": ". CRM es una herramienta de gestión de relaciones con clientes, no de publicidad."},
    {"texto": "El CRM nos ayuda a segmentar mercados.", "respuesta": true,
     "explicacion": ". Permite clasificar clientes según su comportamiento o valor para la empresa."},
    {"texto": "El crowdlending o “microfinanciación” tiene el objetivo de financiar un determinado proyecto a cambio de recompensas.", "respuesta": false,
     "explicacion": ". El crowdlending da préstamos a cambio de intereses, no recompensas como el crowdfunding."},
    {"texto": "El desenlace en una startup es siempre la ruptura de relaciones entre los socios.", "respuesta": false,
     "explicacion": ". Ojo, muchas startups evolucionan, pivotan o son adquiridas, no todas terminan con conflicto."},
    {"texto": "El escape es un método de provocación de ideas que nos lleva a exagerar los atributos de un producto para hacerlo atractivo.", "respuesta": false,
     "explicacion": ". Ojo, el método de exagerar atributos existe, pero se llama 'exageración'. El 'escape' busca eliminar un elemento esencial para generar nuevas ideas."},
    {"texto": "El Estatuto de los trabajadores es la ley que regula todas aquellas cuestiones esenciales vinculadas a la relación laboral, estableciendo derechos y obligaciones tanto para los trabajadores como para los empleadores.", "respuesta": true,
     "explicacion": ". Es la base legal de las relaciones laborales en España: fija derechos, deberes y tipos de contrato."},
    {"texto": "El factoring es un procedimiento financiero por el cual una entidad financiera asume la gestión de los pagos por parte de una empresa hacia sus proveedores en caso de que ésta no pueda hacer frente a dichos pagos en los plazos establecidos por la emisión de la factura.", "respuesta": false,
     "explicacion": ". El factoring gestiona el cobro de facturas pendientes de clientes, no los pagos a proveedores (eso sería confirming)."},
    {"texto": "El Growselling analiza el funcionamiento interno y el de la competencia, en especial de sus políticas de marketing mix y sirve a las empresas como indicadores para establecer buenas prácticas.", "respuesta": false,
     "explicacion": ". Ojo, el término  es benchmarking; growselling no es un concepto académico reconocido."},
    {"texto": "El impuesto del IVA forma parte del PVP (precio venta público).", "respuesta": true,
     "explicacion": ". El IVA se suma al precio base y por tanto forma parte del precio de venta al público."},
    {"texto": "El leasing es un contrato de arrendamiento a largo plazo con opción a compra una vez finalizado el contrato.", "respuesta": true,
     "explicacion": ". Ojo, no confundir con renting: en leasing sí hay opción de compra."},
    {"texto": "El líder liberal delegan la responsabilidad a expertos capacitados.", "respuesta": false,
     "explicacion": ". El líder liberal apenas interviene ni guía; delega sin supervisar, lo que puede ser ineficiente."},
    {"texto": "El líder relacional está orientado a la tarea.", "respuesta": false,
     "explicacion": ". Está orientado a las personas y a mantener buenas relaciones, no a la tarea."},
    {"texto": "El liderazgo natural es una forma extrema de liderazgo transaccional, donde los líderes tienen el poder absoluto sobre sus trabajadores o equipos.", "respuesta": false,
     "explicacion": ". Ojo, eso describe liderazgo autoritario; el natural surge por carisma, no por jerarquía."},
    {"texto": "El mapa de posicionamiento es una herramienta que permite visualizar los elementos diferenciadores de un producto y la posición que ocupan los productos competidores.", "respuesta": true,
     "explicacion": ". Se usa para ver cómo te perciben frente a la competencia según dos variables clave (precio, calidad, etc.)."},
    {"texto": "El margen neto es un coste directo.", "respuesta": false,
     "explicacion": ". El margen neto es un resultado, no un coste: mide lo que queda tras restar todos los gastos."},
    {"texto": "El marketing estratégico define las líneas generales de actuación y se ocupa de las actividades que pretenden analizar y conocer las necesidades del consumidor para establecer un plan de marketing a corto plazo.", "respuesta": false,
     "explicacion": ". El estratégico trabaja a medio/largo plazo; el de corto es el operativo."},
    {"texto": "El marketing social tiene por objetivo promover la adaptación de comportamientos sociales que se consideran beneficiosos para la sociedad en general.", "respuesta": true,
     "explicacion": ". Persigue cambios positivos en salud, medioambiente o civismo."},
    {"texto": "El márqueting estratégico define las acciones a llevar a cabo y las herramientas que se pueden utilizar para conseguir los objetivos establecidos en el plan de marketing con relación al marketing mix para un período de tiempo determinado.", "respuesta": false,
     "explicacion": ". Ojo, eso es marketing operativo; el estratégico marca las grandes decisiones."},
    {"texto": "El márqueting estratégico requiere revisar como es mi producto, mi organización y mis costes.", "respuesta": true,
     "explicacion": ". Es análisis interno para detectar fortalezas y ajustar estrategias."},
    {"texto": "El márqueting político está considerado como márqueting de servicios.", "respuesta": false,
     "explicacion": ". Se relaciona con marketing social, no con marketing de servicios."},
    {"texto": "El márqueting relacional no busca aumentar el tiquet medio de compra.", "respuesta": false,
     "explicacion": ". Ojo, sí busca aumentar el ticket medio fidelizando al cliente."},
    {"texto": "El márqueting social lo usan únicamente asociaciones o empresas sin ánimo de lucro.", "respuesta": false,
     "explicacion": ". También lo aplican empresas privadas con campañas de responsabilidad social."},
    {"texto": "El mercado de consumo es aquel formado por organizaciones, empresas e instituciones.", "respuesta": false,
     "explicacion": ". Ese es el mercado industrial; el de consumo está formado por particulares."},
    {"texto": "El mercado potencial es un conjunto de personas u organizaciones de los consumidores en grupos homogéneos en función de sus características.", "respuesta": true,
     "explicacion": ". Define el conjunto total de posibles compradores."},
    {"texto": "El microcrédito es un tipo de financiación para empresas y emprendedores que consiste en el aplazamiento del pago de una compraventa.", "respuesta": false,
     "explicacion": ". Ojo, eso describe crédito comercial; el microcrédito es un préstamo pequeño."},
    {"texto": "El microcrédito es un tipo de préstamo de poca cantidad destinado tanto para personas físicas como para la financiación de empresas y proyectos sociales.", "respuesta": true,
     "explicacion": ". Es su definición clásica: préstamo pequeño para autoempleo o emprendimiento."},
    {"texto": "El miedo es una emoción desagradable de alta intensidad.", "respuesta": false,
     "explicacion": ". Es de intensidad variable; se considera una emoción básica, no necesariamente alta siempre."},
    {"texto": "El modelo de negocio define que hacemos y cómo lo hacemos.", "respuesta": false,
     "explicacion": ". Ojo, también debe definir cómo generamos ingresos y aportamos valor."},
    {"texto": "El monopolio bilateral ocurre cuando el mercado tiene poca oferta y poca demanda.", "respuesta": false,
     "explicacion": ". Eso describe un mercado restringido, no un monopolio bilateral, que es un solo oferente y un solo demandante."},
    {"texto": "El nivel de calidad de la atención telefónica a los clientes se mide por la amplitud de operadores, horarios de servicio, trato con los clientes y rápida respuesta a sus requerimientos.", "respuesta": true,
     "explicacion": ". Son indicadores típicos de calidad en atención al cliente."},
    {"texto": "El objetivo de la segmentación de mercados es aplicar una estrategia comercial uniforme, lo que hará más efectivas las acciones de marketing.", "respuesta": false,
     "explicacion": ". Ojo, justo al revés: se segmenta para aplicar estrategias diferenciadas, no uniformes."},
    {"texto": "El objetivo de la segmentación del mercado es conseguir que cada tipo de cliente compre el producto que le corresponde por ingresos.", "respuesta": false,
     "explicacion": ". No se basa en ingresos únicamente, sino en necesidades y comportamientos."},
    {"texto": "El objetivo de los ratios es simplificar el análisis de gestión.", "respuesta": true,
     "explicacion": ". Los ratios resumen la situación económica o de rendimiento de forma rápida."},
    {"texto": "El objetivo de usar un producto mínimo viable es aprender de los clientes.", "respuesta": true,
     "explicacion": ". Ojo, no es vender rápido, sino validar hipótesis con el menor coste."},
    {"texto": "El periodo de adecuación de un trabajador debe ser corto, confortable y consistente.", "respuesta": false,
     "explicacion": ". Debe ser suficiente para adaptarse, no necesariamente corto."},
    {"texto": "El plan de carrera es el proyecto personal de formación y objetivos de trabajo que la empresa traza para un trabajador, con el propósito de formar, publicitar y dar seguridad.", "respuesta": true,
     "explicacion": ". Sirve para desarrollar talento y motivar al empleado."},
    {"texto": "El PMV Mago de Oz consiste en hacer creer a los clientes que dispongo de toda la infraestructura de un servicio, sin que la haya desarrollado pero el cliente recibe el servicio.", "respuesta": true,
     "explicacion": ". Es un PMV donde simulas el funcionamiento del servicio para validar interés."},
    {"texto": "El PMV Mago de Oz consiste en hacer creer a los clientes que voy a prestar un servicio, sin que este realmente exista. Si el interés es alto, se desarrolla el producto.", "respuesta": false,
     "explicacion": ". Ojo, en el Mago de Oz el cliente sí recibe el servicio, aunque detrás haya procesos manuales."},
    {"texto": "El PMV maqueta me sirve para que los clientes puedan interactuar con él y su feedback sea más efectivo.", "respuesta": true,
     "explicacion": ". Una maqueta o prototipo permite medir reacciones y mejorar el diseño."},
    {"texto": "El posicionamiento de mercado de una empresa para un producto concreto tiene que ver con el éxito de sus campañas de publicidad.", "respuesta": false,
     "explicacion": ". El posicionamiento depende de cómo el público percibe la marca, no solo de la publicidad."},
    {"texto": "El posicionamiento de una marca se determina con el precio de la misma.", "respuesta": false,
     "explicacion": ". Ojo, el precio influye, pero el posicionamiento incluye imagen, calidad y valores percibidos."},
    {"texto": "El prescriptor, por su conocimiento y su experiencia, influye sobre el consumo o la compra de un producto o servicio.", "respuesta": true,
     "explicacion": ". Los prescriptores pueden ser expertos, médicos, influencers o líderes de opinión."},
    {"texto": "El principal objetivo de las empresas debe ser el de perdurar en el tiempo.", "respuesta": false,
     "explicacion": ". Ojo, su fin principal es satisfacer necesidades y generar valor; la supervivencia es consecuencia."},
    {"texto": "El principal objetivo de las empresas debe ser el de satisfacer las necesidades de los clientes y de los grupos de interés, abundando la responsabilidad social corporativa.", "respuesta": true,
     "explicacion": ". Resume el enfoque moderno de sostenibilidad y valor compartido."},
    {"texto": "El principal objetivo de las empresas debe ser la maximización del beneficio a largo plazo.", "respuesta": false,
     "explicacion": ". Ojo, ese es un enfoque antiguo; hoy se prioriza sostenibilidad y stakeholders."},
    {"texto": "El proceso comercial tiene 2 fases: atraer y vender.", "respuesta": false,
     "explicacion": ". Incluye más fases: prospección, preparación, presentación, objeciones, cierre y seguimiento."},
    {"texto": "El proceso de dirección tiene una fase estática y una fase dinámica.", "respuesta": true,
     "explicacion": ". La fase estática planifica; la dinámica ejecuta y controla."},
    {"texto": "El producto mínimo viable es un producto provisional con las mínimas características necesarias, que nos permita analizar al mercado.", "respuesta": true,
     "explicacion": ". Es una versión básica para validar hipótesis rápidamente."},
    {"texto": "El renting es un contrato para adquirir la maquinaria o vehículo mediante el pago de una cuantía mensual.", "respuesta": true,
     "explicacion": ". Ojo, en renting no hay opción de compra al final del contrato."},
    {"texto": "El resultado en las empresas puede ser de beneficio o pérdidas.", "respuesta": true,
     "explicacion": ". Es la diferencia entre ingresos y gastos totales."},
    {"texto": "El sentimiento es la racionalización de la emoción que hemos captado de forma “animal”.", "respuesta": true,
     "explicacion": ". El sentimiento es la interpretación consciente de una emoción."},
    {"texto": "El sombrero blanco en la técnica de generación de ideas de los 6 sombreros, representa el pensamiento positivo, las ventajas y valores.", "respuesta": false,
     "explicacion": ". Ojo, el blanco representa datos y hechos objetivos; el amarillo es el positivo."},
    {"texto": "El tamaño de mercado lo podemos definir como: Número de dientes * cantidad usada * veces que se compra.", "respuesta": true,
     "explicacion": ". Es un ejemplo didáctico de cómo estimar el tamaño de mercado con datos cuantificables."},
    {"texto": "El tamaño de mercado queda condicionado por los horarios que abren las tiendas.", "respuesta": false,
     "explicacion": ". Ojo, eso puede afectar ventas, pero no define el tamaño total del mercado."},
    {"texto": "El Teflón o los Post-it son buenos ejemplos del método de generación de ideas, tipo provocación de ideas.", "respuesta": true,
     "explicacion": ". Surgieron por error o casualidad aplicando el principio de provocar nuevas combinaciones."},
    {"texto": "El temor de la población al Covid-19 es una buena oportunidad para generar nuevos negocios.", "respuesta": true,
     "explicacion": ". Ojo, esto se refiere a detectar nuevas necesidades (mascarillas, apps sanitarias...), no a aprovecharse del miedo en sí."},
    {"texto": "El test de humo (PMV) se basa en una web con la descripción de una herramienta y lo que podía hacer por ti.", "respuesta": false,
     "explicacion": ". Ojo, ese ejemplo es incompleto: el test de humo consiste en ofrecer un producto que aún no existe para medir interés."},
    {"texto": "El test de humo, el crowdfunding y la landing page (PMV) se parecen en que los productos ofrecidos no existen y lo más importante es saber cuántos usuarios están interesados.", "respuesta": true,
     "explicacion": ". Todas estas herramientas buscan validar demanda antes de fabricar nada."},
    {"texto": "El up selling es ofrecer productos o servicios complementarios a los clientes habituales para generar valor añadido.", "respuesta": false,
     "explicacion": ". Ojo, eso es cross selling; el up selling busca vender una versión más cara del mismo producto."},
    {"texto": "El valle de la muerte relaciona el tiempo y los ingresos en una startup.", "respuesta": false,
     "explicacion": ". Ojo, relaciona el tiempo con la liquidez: el momento en que los gastos superan a los ingresos iniciales."},
    {"texto": "El Venture Capital son individuos que invierten su capital en empresas nuevas a cambio de participación accionaria.", "respuesta": false,
     "explicacion": ". Los individuos son business angels; el Venture Capital son fondos profesionales."},
    {"texto": "Elton Mayo fue un precursor de la escuela de relaciones humanas en el trabajo.", "respuesta": true,
     "explicacion": ". Sus experimentos en Hawthorne demostraron la importancia de los factores sociales en la productividad."},
    {"texto": "Empresario es aquel que administra una empresa.", "respuesta": false,
     "explicacion": ". Ojo, un empresario es quien asume riesgos y toma decisiones, no solo administra."},
    {"texto": "En Catalunya existe el Projecte FOCUS sobre los 8 focos de la Responsabilidad Social Corporativa, que incluyen ética, comunidad, territorio y economía circular.", "respuesta": true,
     "explicacion": ". Es una iniciativa catalana que agrupa los ejes de la RSC."},
    {"texto": "En Catalunya existe el Projecte FOCUS que incluye generación de ocupación, desarrollo del capital humano, desarrollo económico responsable y cohesión social.", "respuesta": true,
     "explicacion": ". Resume los ejes principales del programa catalán de RSC."},
    {"texto": "En el análisis DAFO, la D significa Demografía.", "respuesta": false,
     "explicacion": ". Ojo, la D es de Debilidades; la demografía se estudia en el análisis PESTEL."},
    {"texto": "En el análisis DAFO, la F significa Fabricación.", "respuesta": false,
     "explicacion": ". F significa Fortalezas, no tiene nada que ver con producción."},
    {"texto": "En el confirming te anticipan el capital de las facturas pendientes de cobro a cambio de un interés.", "respuesta": false,
     "explicacion": ". Ojo, eso es factoring; el confirming gestiona pagos a proveedores, no cobros."},
    {"texto": "En el crowdfunding se trata de conectar online empresas que requieren capital con inversores.", "respuesta": false,
     "explicacion": ". Eso es crowdlending o equity crowdfunding; el clásico crowdfunding busca pequeñas aportaciones a cambio de recompensas."},
    {"texto": "En el desarrollo de nuevos productos, un producto de plataforma viene de un descubrimiento o avance tecnológico.", "respuesta": false,
     "explicacion": ". Los productos de plataforma comparten base con otros; los que vienen de avances son los de ruptura."},
    {"texto": "En el factoring te anticipan el capital de facturas pendientes a cambio de un interés.", "respuesta": true,
     "explicacion": ". El factoring es financiación basada en cobros futuros."},
    {"texto": "En la herramienta CANVAS, el flujo de ingresos debe detallar solo el modo de pago.", "respuesta": false,
     "explicacion": ". Ojo, el bloque de ingresos incluye también fuentes, frecuencia y valor percibido."},
    {"texto": "En la herramienta CANVAS, el segmento de clientes debe cuantificarse con edad, sexo, ingresos y ubicación.", "respuesta": true,
     "explicacion": ". Se trata de definir el perfil de cliente objetivo con variables demográficas y conductuales."},
    {"texto": "En la herramienta CANVAS, el segmento de relación con clientes sirve para explicar la publicidad.", "respuesta": false,
     "explicacion": ". Ojo, ese bloque trata del tipo de relación: personal, automática, autoservicio, etc."},
    {"texto": "En el neuromárqueting se hacen resonancias magnéticas del cerebro para observar reacciones ante estímulos publicitarios.", "respuesta": true,
     "explicacion": ". Es una técnica real de medición del impacto emocional del marketing."},
    {"texto": "En el préstamo bancario siempre se requiere una garantía.", "respuesta": true,
     "explicacion": ". Puede ser personal o real, pero siempre hay una forma de garantía."},
    {"texto": "En la compra de un frigorífico, ofrecer 6 meses de financiación sin coste es una estrategia de diferenciación en servicios.", "respuesta": true,
     "explicacion": ". Es un valor añadido que mejora la percepción del producto."},
    {"texto": "En la construcción de una empresa, la fase de conocimiento incluye el desarrollo de la idea y los objetivos.", "respuesta": true,
     "explicacion": ". Es la etapa inicial de análisis y definición de la propuesta."},
    {"texto": "En la empresa puedo considerar equivalentes Gasto y Pérdida.", "respuesta": false,
     "explicacion": ". Ojo, un gasto no siempre implica pérdida; puede ser inversión o coste productivo."},
    {"texto": "En la escuela de organización científica del trabajo, Henry Fayol interrelaciona el factor humano y el productivo.", "respuesta": true,
     "explicacion": ". Fayol desarrolló funciones administrativas que integran personas y procesos."},
    {"texto": "En la escuela de organización científica del trabajo, Henry Fayol racionaliza el trabajo para aumentar la productividad.", "respuesta": false,
     "explicacion": ". Ojo, eso fue Taylor; Fayol se centró en la gestión y organización empresarial."},
    {"texto": "En la propiedad intelectual, los Derechos Patrimoniales corresponden al autor por la exclusividad de explotación durante un tiempo limitado.", "respuesta": true,
     "explicacion": ". Son los derechos económicos del autor sobre su obra."},
    {"texto": "En la RSC, el compromiso de las 3 P se refiere a personas, planeta y beneficios.", "respuesta": true,
     "explicacion": ". Es la triple bottom line: people, planet, profit."},
    {"texto": "En las empresas con RSC es buena gestión tener un comité responsable de asegurar compromisos.", "respuesta": true,
     "explicacion": ". Un comité de RSC garantiza seguimiento y coherencia."},
    {"texto": "En márqueting estratégico, la estrategia de diferenciación busca que el producto sea percibido de forma distinta al resto.", "respuesta": true,
     "explicacion": ". Se basa en ventajas únicas percibidas por el consumidor."},
    {"texto": "En mercados de segmentación diferenciada, la distribución y publicidad son generalmente masivas.", "respuesta": false,
     "explicacion": ". Ojo, en ese tipo de mercado se adaptan estrategias por segmento, no masivas."},
    {"texto": "En un leasing la entidad bancaria dispone una cantidad máxima de dinero para usar según necesidad.", "respuesta": false,
     "explicacion": ". Ojo, eso describe una póliza de crédito, no un leasing."},
    {"texto": "En un PMV debemos eliminar todo lo que no aporte valor.", "respuesta": true,
     "explicacion": ". Esa es la esencia del producto mínimo viable."},
    {"texto": "En una póliza de crédito la entidad bancaria dispone una cantidad máxima de dinero para usar según necesidad.", "respuesta": true,
     "explicacion": ". Se paga interés solo por el dinero usado, no por el total disponible."},
    {"texto": "En una Startup se puede pivotar en cualquier momento del proceso de creación.", "respuesta": true,
     "explicacion": ". Pivotar es ajustar el rumbo en base a aprendizaje validado."},
    {"texto": "Es aconsejable dejar de pivotar una empresa antes de tener un PMV que mejore el modelo de negocio.", "respuesta": false,
     "explicacion": ". Ojo, nunca se deja de pivotar sin validar hipótesis con un PMV real."},
    {"texto": "Es tan importante descubrir una idea de negocio como generar un PMV y ponerlo en circulación.", "respuesta": true,
     "explicacion": ". Una idea sin validación no sirve; el PMV da el aprendizaje real."},
    {"texto": "FFF significa Friends, Family and Finance.", "respuesta": false,
     "explicacion": ". Ojo, la tercera F es Fools (locos), no Finance; se refiere a los primeros inversores cercanos."},
    {"texto": "Fomentar el trabajo en equipo es salario emocional.", "respuesta": true,
     "explicacion": ". Mejora la motivación y el ambiente laboral sin requerir aumento económico."},
    {"texto": "Fondo de Maniobra Real = Activo corriente − Pasivo corriente.", "respuesta": true,
     "explicacion": ". Si el resultado es positivo, hay equilibrio financiero a corto plazo."},
    {"texto": "Hay dos elementos que aseguran el éxito de la RSC: código de valores e incentivos económicos.", "respuesta": true,
     "explicacion": ". Ojo, el segundo elemento suele ser incentivos o mecanismos de evaluación."},
    {"texto": "Inversión es la distribución de gasto en un periodo determinado, de un valor duradero.", "respuesta": false,
     "explicacion": ". Ojo, eso es amortización; la inversión es el desembolso inicial."},
    {"texto": "Justicia es dar al prójimo lo que es debido con equidad respecto a individuos y bien común.", "respuesta": true,
     "explicacion": ". Es una de las virtudes cardinales en ética y liderazgo."},
    {"texto": "Kia y sus 7 años de garantía usan una estrategia de especialización en un segmento.", "respuesta": false,
     "explicacion": ". Ojo, es una estrategia de diferenciación, no de especialización."},
    {"texto": "La cadena de valor de Porter analiza actividades de la empresa y cómo aportan valor al cliente.", "respuesta": true,
     "explicacion": ". Permite identificar dónde se genera valor o se desperdician recursos."},
    {"texto": "La creatividad es un objetivo importante para conseguir ventaja competitiva.", "respuesta": true,
     "explicacion": ". Favorece la innovación y diferencia a la empresa de sus competidores."},
    {"texto": "La creatividad surge de la inspiración, el aburrimiento y la observación cotidiana.", "respuesta": true,
     "explicacion": ". Ojo, muchas ideas surgen de la observación y conexión de cosas comunes."},
    {"texto": "La creatividad sistemática es fruto de la inspiración.", "respuesta": false,
     "explicacion": ". Ojo, la creatividad sistemática se entrena con técnicas estructuradas, no depende de la inspiración."},
    {"texto": "La crisis del COVID-19 ha frenado el turismo de sol y playa; para un hotel en Lloret sería una oportunidad (DAFO).", "respuesta": false,
     "explicacion": ". Es una amenaza, no una oportunidad; te la pueden liar con eso en el examen."},
    {"texto": "La Cuenta de Resultados permite conocer la evolución económica de la empresa en un periodo.", "respuesta": true,
     "explicacion": ". Muestra ingresos, gastos y beneficios en un periodo determinado."},
    {"texto": "La cuenta de Resultados es un documento estático que representa la situación económica y financiera.", "respuesta": false,
     "explicacion": ". Es dinámico porque refleja movimientos durante un periodo, no una foto fija."},
    {"texto": "La cuota de mercado es el lugar que ocupa una empresa en un mercado según datos objetivos.", "respuesta": false,
     "explicacion": ". Ojo, la cuota es un porcentaje de ventas respecto al total, no una posición jerárquica."},
    {"texto": "La desalineación de expectativas suele causar conflictos entre socios en startups.", "respuesta": true,
     "explicacion": ". Es una de las principales causas de ruptura en proyectos nuevos."},
    {"texto": "La diferencia entre un prototipo y una maqueta es que el prototipo permite entender el uso real del producto.", "respuesta": true,
     "explicacion": ". La maqueta es visual; el prototipo es funcional."},
    {"texto": "La distribución es el conjunto de tareas necesarias para trasladar productos terminados a los puntos de venta.", "respuesta": true,
     "explicacion": ". Incluye transporte, almacenamiento y logística comercial."},
    {"texto": "La economía circular busca repensar, rediseñar, refabricar y reparar.", "respuesta": true,
     "explicacion": ". Es la base del modelo circular: extender el ciclo de vida del producto para reducir residuos."},
    {"texto": "La eficiencia no tiene en cuenta los recursos empleados.", "respuesta": false,
     "explicacion": ". Ojo, justo al revés: eficiencia es lograr el objetivo usando los mínimos recursos posibles."},
    {"texto": "La eficiencia productiva puede considerarse una herramienta de creatividad e innovación interna.", "respuesta": true,
     "explicacion": ". Mejorar procesos fomenta innovación y reduce desperdicio."},
    {"texto": "La expectativa es un estado de ánimo de quien espera que algo suceda.", "respuesta": false,
     "explicacion": ". Ojo, eso sería esperanza o deseo; expectativa es una creencia sobre lo que ocurrirá."},
    {"texto": "La falta de talento de un socio fundador es fuente habitual de conflictos.", "respuesta": true,
     "explicacion": ". Ojo, no solo por capacidad técnica sino por falta de compromiso o comunicación."},
    {"texto": "La fortaleza es la firmeza ante las dificultades.", "respuesta": true,
     "explicacion": ". Es una de las virtudes cardinales junto con prudencia, justicia y templanza."},
    {"texto": "La función de la organización permite que los planes se hagan realidad con la colaboración de todos.", "respuesta": true,
     "explicacion": ". Organizar coordina recursos y personas para ejecutar los planes."},
    {"texto": "La guardería para hijos de trabajadores es una remuneración monetaria.", "respuesta": true,
     "explicacion": ". Ojo, eso es una retribución en especie, no monetaria."},
    {"texto": "La innovación incremental se realiza mediante pequeñas mejoras en productos o servicios.", "respuesta": true,
     "explicacion": ". Es la más común: mejoras graduales, no rupturas."},
    {"texto": "La Mano de Obra Indirecta debe considerarse gasto para obtener el Margen Bruto.", "respuesta": true,
     "explicacion": ". Ojo, no se incluye en coste directo del producto, pero afecta al margen global."},
    {"texto": "La misión de una startup es descubrir lo antes posible su modelo de negocio al menor coste.", "respuesta": true,
     "explicacion": ". Ese es su objetivo antes de escalar: validar hipótesis rápido."},
    {"texto": "La organización del trabajo coordina todos los medios de la empresa para lograr objetivos con mínimo coste.", "respuesta": true,
     "explicacion": ". Es la base de la eficiencia operativa."},
    {"texto": "La organización formal son las relaciones personales y sociales no establecidas por la dirección.", "respuesta": false,
     "explicacion": ". Ojo, eso sería la organización informal; la formal es la jerárquica."},
    {"texto": "La Organización Mundial de la Propiedad Intelectual fue creada en 1967.", "respuesta": true,
     "explicacion": ". Es el organismo de la ONU encargado de regular la propiedad intelectual global."},
    {"texto": "La orientación al cliente a largo plazo se convierte en fidelización.", "respuesta": true,
     "explicacion": ". La atención constante y personalizada genera lealtad."},
    {"texto": "La propiedad intelectual sobre una marca se puede mantener eternamente.", "respuesta": true,
     "explicacion": ". Ojo, siempre que se renueve periódicamente y se use comercialmente."},
    {"texto": "La propiedad intelectual son creaciones derivadas del talento humano protegidas por normas jurídicas.", "respuesta": true,
     "explicacion": ". Incluye obras literarias, artísticas, inventos y marcas."},
    {"texto": "La Responsabilidad Social Corporativa es una forma de dirigir las empresas basada en la gestión de los impactos sobre la sociedad.", "respuesta": true,
     "explicacion": ". Va más allá del beneficio económico: implica compromiso ético y sostenible."},
    {"texto": "La técnica de eye-tracking analiza el recorrido visual del ojo ante publicidad.", "respuesta": true,
     "explicacion": ". Se usa en neuromarketing para medir atención y emociones."},
    {"texto": "Las 4 principales herramientas necesarias para crear una startup son creatividad, entusiasmo, formación y experiencia.", "respuesta": true,
     "explicacion": ". Ojo, sin formación y pasión, la creatividad no basta."},
    {"texto": "Las características de un segmento de mercado deben ser medible, accesible, diferenciable, sustancial y estable.", "respuesta": true,
     "explicacion": ". Son los criterios clásicos de una buena segmentación."},
    {"texto": "Las conexiones forzadas son un método creativo que combina productos existentes para crear uno nuevo.", "respuesta": true,
     "explicacion": ". Es una técnica para generar ideas mediante asociaciones inesperadas."},
    {"texto": "Las deudas a largo plazo son un pasivo corriente.", "respuesta": false,
     "explicacion": ". Ojo, las de largo plazo son pasivo no corriente."},
    {"texto": "Las empresas deben tener en cuenta los gustos y opiniones de los clientes.", "respuesta": true,
     "explicacion": ". Ojo, esto parece obvio pero es la base del marketing actual."},
    {"texto": "Las empresas pueden declarar como activo las patentes que poseen.", "respuesta": true,
     "explicacion": ". Son activos intangibles registrados en el balance."},
    {"texto": "Las existencias son un activo corriente.", "respuesta": true,
     "explicacion": ". Son bienes destinados a la venta o transformación a corto plazo."},
    {"texto": "Las hipótesis a validar por un PMV son si genera interés y permite desarrollar el negocio.", "respuesta": true,
     "explicacion": ". Ojo, también si los clientes están dispuestos a pagar por él."},
    {"texto": "Las indicaciones geográficas identifican productos cuyas cualidades se deben a su origen.", "respuesta": true,
     "explicacion": ". Ejemplo clásico: el vino Rioja o el queso Manchego."},
    {"texto": "Las licitaciones y concursos de servicios son estrategias competitivas para la fijación de precios.", "respuesta": true,
     "explicacion": ". Son métodos de mercado público donde el precio y la propuesta compiten."},
    {"texto": "Las patentes son un derecho exclusivo concedido sobre una invención.", "respuesta": true,
     "explicacion": ". Protegen una solución técnica nueva, útil y no obvia."},
    {"texto": "Las plataformas de crowdfunding sirven para financiar proyectos.", "respuesta": true,
     "explicacion": ". Ojo, financian a través de pequeñas aportaciones colectivas."},
    {"texto": "Las startups tienen como misión principal ganar dinero.", "respuesta": false,
     "explicacion": ". Su objetivo es validar un modelo de negocio; los beneficios vienen después."},
    {"texto": "Las variables del marketing mix son producto, precio, producción y posicionamiento.", "respuesta": false,
     "explicacion": ". Ojo, las 4 P son producto, precio, plaza (distribución) y promoción."},
    {"texto": "Las virtudes cardinales son 4: fortaleza, habilidad, justicia y conocimiento.", "respuesta": false,
     "explicacion": ". Son fortaleza, justicia, prudencia y templanza; te la pueden liar con los términos."},
    {"texto": "Lo que no se puede medir no se puede mejorar.", "respuesta": true,
     "explicacion": ". Frase de gestión clásica: sin métricas no hay mejora posible."},
    {"texto": "Los 5 principios de la RSC son: cumplimiento de la ley, visión global, ética y coherencia, gestión de impactos y satisfacción de expectativas.", "respuesta": true,
     "explicacion": ". Son las bases para implementar una RSC real y coherente."},
    {"texto": "Los acreedores comerciales son un pasivo corriente.", "respuesta": true,
     "explicacion": ". Son deudas a corto plazo con proveedores."},
    {"texto": "Los bienes de consumo duradero son aquellos que no se destruyen con su uso.", "respuesta": true,
     "explicacion": ". Ejemplo: coche, nevera, ordenador... duran varios años."},
    {"texto": "Los Business Angel invierten cifras pequeñas en startups (no suelen superar 500 000 €).", "respuesta": true,
     "explicacion": ". Ojo, son particulares con capital propio, no fondos institucionales."},
    {"texto": "Los clientes solo quieren satisfacer sus necesidades de forma eficiente.", "respuesta": true,
     "explicacion": ". Aunque también valoran emociones o valores de marca."},
    {"texto": "Los conceptos matemáticos no se pueden proteger con derechos de autor.", "respuesta": true,
     "explicacion": ". Ojo, las ideas o fórmulas no se protegen, solo su aplicación o expresión."},
    {"texto": "Los convenios de empresa son acuerdos entre representantes de trabajadores y empresa para regular condiciones laborales.", "respuesta": true,
     "explicacion": ". Pueden complementar o mejorar el convenio sectorial."},
    {"texto": "Los derechos morales reconocen al autor por la obra y no se pueden ceder ni renunciar.", "respuesta": true,
     "explicacion": ". Son inherentes al autor: paternidad, integridad y divulgación."},
    {"texto": "Los líderes transformacionales inspiran y transmiten entusiasmo a su equipo.", "respuesta": true,
     "explicacion": ". Ojo, se centran en la motivación y el desarrollo personal del grupo."},
    {"texto": "Los Venture Capital buscan invertir en startups atractivas con modelos desarrollados que necesitan capital para crecer.", "respuesta": true,
     "explicacion": ". Invierten en etapas de expansión con alto potencial de retorno."},
    {"texto": "Para buscar un socio, hay que elegir personas expertas en las áreas clave del proyecto.", "respuesta": true,
     "explicacion": ". Ojo, no basta con afinidad personal: debe aportar valor real al negocio."},
    {"texto": "Para captar y retener talento es importante disponer de un plan de acogida.", "respuesta": true,
     "explicacion": ". Un buen onboarding mejora adaptación y compromiso."},
    {"texto": "Para diseñar un buen sistema de organización hay que determinar las jerarquías de los mandos.", "respuesta": true,
     "explicacion": ". Definir niveles de responsabilidad evita confusiones y solapamientos."},
    {"texto": "Para el consumidor, el precio representa el esfuerzo que debe hacer para conseguir el producto.", "respuesta": true,
     "explicacion": ". El precio se percibe como sacrificio económico, emocional o de tiempo."},
    {"texto": "Para justificar el coste de una visita comercial, el beneficio mínimo del pedido debe superar dicho coste.", "respuesta": true,
     "explicacion": ". Si no, la acción comercial no es rentable."},
    {"texto": "Para tener éxito en un proyecto emprendedor es imprescindible contar con personas expertas.", "respuesta": true,
     "explicacion": ". Ojo, el equipo es tan clave como la idea o la financiación."},
    {"texto": "Para una empresa es importante que sus clientes expresen sus quejas y disconformidades.", "respuesta": true,
     "explicacion": ". Ojo, los reclamos son una oportunidad de mejora; lo peligroso es el cliente que no se queja y se va."},
    {"texto": "Participación paritaria en una sociedad es aquella en la que todos los socios son iguales y tienen los mismos derechos.", "respuesta": true,
     "explicacion": ". Significa que cada socio tiene igual porcentaje de participación y voto."},
    {"texto": "Peeble fue un buen ejemplo de Mago de Oz (PMV).", "respuesta": false,
     "explicacion": ". Peeble fue crowdfunding, no Mago de Oz. Vendieron relojes antes de fabricarlos para medir demanda."},
    {"texto": "Pivotar es una corrección estructurada para probar una nueva hipótesis sobre el producto o el modelo de negocio.", "respuesta": true,
     "explicacion": ". Ojo, pivotar no es empezar de cero: es ajustar con base en aprendizaje validado."},
    {"texto": "Plantearse continuamente el 'por qué' de cada cosa y programar cambios deliberados forma parte de la creatividad sistemática.", "respuesta": true,
     "explicacion": ". La creatividad sistemática se entrena con cuestionamientos intencionados, no con inspiración espontánea."},
    {"texto": "Que exista una necesidad es la principal puerta para vender algo.", "respuesta": true,
     "explicacion": ". Si no hay necesidad, no hay mercado; ojo, el deseo también puede crearla."},
    {"texto": "Quien contrata un leasing asume los gastos derivados como impuestos y averías.", "respuesta": true,
     "explicacion": ". A diferencia del renting, en leasing el arrendatario se hace cargo del mantenimiento."},
    {"texto": "Relaciones públicas son incentivos a corto plazo que fomentan la compra o venta de un producto o servicio.", "respuesta": false,
     "explicacion": ". Ojo, eso describe promoción de ventas; RRPP es gestión de imagen y reputación."},
    {"texto": "Responsabilidad Social Corporativa es la obligación ética y moral voluntariamente aceptada por la empresa hacia la sociedad.", "respuesta": true,
     "explicacion": ". Es una gestión ética de los impactos sociales y ambientales."},
    {"texto": "Samsung comenzó vendiendo pescado seco, verduras y fideos antes de dedicarse a la electrónica.", "respuesta": true,
     "explicacion": ". Curioso pero cierto: empezó como empresa comercial de exportación."},
    {"texto": "Según Drucker, las ideas surgen por lo inesperado, la incongruencia o una necesidad de proceso.", "respuesta": true,
     "explicacion": ". Drucker identificó fuentes de innovación como cambios, incongruencias o sucesos inesperados."},
    {"texto": "Según Kotler, un producto es todo lo que se puede ofrecer a un mercado para su adquisición, uso o consumo.", "respuesta": true,
     "explicacion": ". Es la definición clásica de producto según Kotler."},
    {"texto": "Según la matriz de Ansoff, el desarrollo de mercados sucede con productos nuevos en mercados existentes.", "respuesta": false,
     "explicacion": ". Ojo, eso es desarrollo de producto; desarrollo de mercado es vender lo mismo en nuevos mercados."},
    {"texto": "Según la pirámide de Maslow, las necesidades sociales o de prestigio tienen que ver con la pertenencia a grupos u organizaciones.", "respuesta": false,
     "explicacion": ". Ojo, las de pertenencia son las sociales; las de prestigio son reconocimiento y estatus."},
    {"texto": "Según la posición competitiva, si Netflix es líder en distribución de contenidos, HBO o Amazon Prime Video son retadoras.", "respuesta": true,
     "explicacion": ". Se clasifican como empresas retadoras por competir directamente con el líder."},
    {"texto": "Según la propiedad intelectual, el derecho de cita permite usar una obra de forma ilimitada citando la fuente.", "respuesta": false,
     "explicacion": ". Ojo, el derecho de cita tiene límites y debe ser con finalidad docente o crítica."},
    {"texto": "Según Maslow, las necesidades más altas que cubrimos son las de estatus y prestigio.", "respuesta": false,
     "explicacion": ". Ojo, la más alta es la autorrealización, no el estatus."},
    {"texto": "Si tres empresas controlan el 60 % del mercado mundial del azúcar, hablamos de monopolio.", "respuesta": false,
     "explicacion": ". Eso es un oligopolio, no un monopolio; hay varios oferentes."},
    {"texto": "Si un producto es caro, podemos asegurar que es de calidad.", "respuesta": false,
     "explicacion": ". Ojo, precio y calidad no siempre están relacionados, aunque el consumidor lo asocie."},
    {"texto": "Si un trabajador cobra 14 pagas y la empresa le ingresa 20 000 € al año, ese es el coste total para la empresa.", "respuesta": false,
     "explicacion": ". El coste total incluye cotizaciones, seguros y cargas sociales."},
    {"texto": "Solo con entusiasmo se pueden conseguir ventajas competitivas sostenibles.", "respuesta": false,
     "explicacion": ". Ojo, el entusiasmo ayuda pero se necesita estrategia, talento y recursos."},
    {"texto": "Todas las startups pueden aprender con un producto mínimo viable, sea cual sea su producto.", "respuesta": false,
     "explicacion": ". En productos complejos o industriales, el PMV puede no ser viable técnicamente."},
    {"texto": "Todos los departamentos de la empresa están orientados a la atención al cliente.", "respuesta": true,
     "explicacion": ". Toda la empresa debe centrarse en generar valor al cliente."},
    {"texto": "Tropicfeel fue un buen ejemplo de crowdfunding (PMV).", "respuesta": true,
     "explicacion": ". Validaron su idea de zapatillas de viaje con campañas de financiación colectiva."},
    {"texto": "Twitter, antes denominado Odeo, era un servicio de podcasting y compartición de audio.", "respuesta": true,
     "explicacion": ". Nació como plataforma de podcasts y pivotó hacia microblogging."},
    {"texto": "Un casino en un barco es un ejemplo de desarrollo de producto que rompe las reglas.", "respuesta": true,
     "explicacion": ". Cambia el contexto del servicio para sortear restricciones legales."},
    {"texto": "Un cliente es quien compra o usa los bienes y servicios de una empresa.", "respuesta": true,
     "explicacion": ". Cliente incluye tanto comprador como usuario."},
    {"texto": "Un cliente que gasta 80 €/semana en el supermercado vale 83 200 € para cualquier empresa.", "respuesta": true,
     "explicacion": ". Es una forma de estimar el valor de vida del cliente (LTV)."},
    {"texto": "Un emprendedor es siempre un empresario.", "respuesta": false,
     "explicacion": ". Ojo, emprendedor puede estar en fase inicial; empresario ya gestiona una empresa establecida."},
    {"texto": "Un jefe y un líder son lo mismo.", "respuesta": false,
     "explicacion": ". Ojo, el jefe manda; el líder inspira y guía."},
    {"texto": "Un líder quiere que crezcas profesionalmente y aportes mejoras a la organización.", "respuesta": true,
     "explicacion": ". El líder impulsa desarrollo, no control."},
    {"texto": "Un lobby es un grupo que trabaja para facilitar actividades de una empresa en la sociedad.", "respuesta": true,
     "explicacion": ". Son grupos de presión legalmente constituidos para influir en decisiones públicas."},
    {"texto": "Un mercado de concurrencia se da con muchos vendedores y muchos compradores.", "respuesta": true,
     "explicacion": ". Es la competencia perfecta del modelo clásico."},
    {"texto": "Un mercado en monopolio es cuando hay un único ofertante y mucha demanda.", "respuesta": true,
     "explicacion": ". Ejemplo típico: monopolios naturales como electricidad o agua."},
    {"texto": "Un mercado es un lugar donde se compran y venden bienes o servicios.", "respuesta": true,
     "explicacion": ". Ojo, no tiene que ser físico: también puede ser digital o virtual."},
    {"texto": "Un modelo de negocio describe cómo la empresa hace atractivos sus productos para ganar dinero.", "respuesta": true,
     "explicacion": ". Resume qué valor ofrece, a quién y cómo obtiene ingresos."},
    {"texto": "Un monopsonio limitado se da en mercados con pocos ofertantes y un solo comprador.", "respuesta": true,
     "explicacion": ". Caso típico: grandes distribuidores comprando a muchos pequeños productores."},
    {"texto": "Un paraguas es un bien de compra habitual o de conveniencia.", "respuesta": true,
     "explicacion": ". Es un producto de adquisición rápida y poco análisis previo."},
    {"texto": "Un PowerPoint o un vídeo pueden ser un producto mínimo viable.", "respuesta": true,
     "explicacion": ". Ojo, si sirven para validar interés, cumplen su función de PMV."},
    {"texto": "Un socio es alguien que aporta algo que el proyecto necesita.", "respuesta": true,
     "explicacion": ". Puede aportar dinero, conocimiento o contactos; no solo capital."},
    {"texto": "Una buena idea lo es todo en un negocio.", "respuesta": false,
     "explicacion": ". Ojo, la ejecución, el equipo y la validación son igual o más importantes."},
    {"texto": "Una categoría de productos es el conjunto de productos que satisfacen de manera similar una necesidad.", "respuesta": true,
     "explicacion": ". Ejemplo: pastas de dientes o detergentes forman categorías distintas."},
    {"texto": "Una empresa con costes fijos de 169 200 € y margen adecuado tiene su punto muerto en 9400 unidades.", "respuesta": true,
     "explicacion": ". Es un ejemplo numérico de equilibrio entre costes y ventas."},
    {"texto": "Una estructura organizativa funcional y matricial solo se diferencian en el número de mandos intermedios.", "respuesta": false,
     "explicacion": ". Ojo, la matricial combina estructura funcional y por proyectos, no solo jerarquía."},
    {"texto": "Una novela puede protegerse con derechos de autor, pero los artículos periodísticos no.", "respuesta": true,
     "explicacion": ". Ojo, ambos se protegen por derechos de autor si son originales."},
    {"texto": "Una oportunidad de mercado existe cuando hay un grupo numeroso con necesidades no satisfechas.", "respuesta": true,
     "explicacion": ". Detectar esas carencias es la base del emprendimiento."},
    {"texto": "Una persona con habilidades necesarias puede ser socio sin aportar capital.", "respuesta": true,
     "explicacion": ". Aporta valor a través de trabajo o conocimiento (socio industrial)."},
    {"texto": "Una sociedad solo se puede fundar si los socios buscan exactamente los mismos objetivos.", "respuesta": false,
     "explicacion": ". Ojo, basta con objetivos compatibles y visión común del proyecto."},
    {"texto": "Una spin-off es una empresa segregada de una unidad empresarial mayor que adquiere vida propia.", "respuesta": true,
     "explicacion": ". Surgen a menudo de universidades o grandes empresas."},
    {"texto": "Una startup es una organización provisional para diseñar y validar un modelo de negocio viable, replicable y escalable.", "respuesta": true,
     "explicacion": ". Es la definición clásica según Eric Ries."},
    {"texto": "Una startup funciona como un conjunto de actividades simultáneas.", "respuesta": true,
     "explicacion": ". Desarrolla producto, busca mercado y financia al mismo tiempo."},
    {"texto": "X, antes denominado Odeo, era un servicio de podcasting personal y compartición de ficheros de audio.", "respuesta": true,
     "explicacion": ". Es la misma historia de Twitter antes del pivotaje."},
    {"texto": "Zappos es un buen ejemplo de crowdfunding (PMV).", "respuesta": false,
     "explicacion": ". Ojo, Zappos usó un PMV tipo Mago de Oz: vendía zapatos online que compraba manualmente tras cada pedido."},
    {"texto": "Las empresas tienen dos objetivos principales: ganar dinero y practicar responsabilidad social corporativa.", "respuesta": true,
     "explicacion": ". Hoy el equilibrio entre rentabilidad y compromiso social define la sostenibilidad empresarial."},
    {"texto": "Las patentes dan derechos de protección internacionales automáticamente.", "respuesta": false,
     "explicacion": ". Ojo, la patente es territorial: hay que registrarla en cada país o a través del sistema internacional."},
    {"texto": "Los precios muy bajos generan sospechas de baja calidad en el comprador potencial.", "respuesta": true,
     "explicacion": ". Ojo, el consumidor asocia muchas veces precio con calidad percibida."},
    {"texto": "Los precios se establecen según la oferta y la demanda.", "respuesta": true,
     "explicacion": ". Es la base del mercado libre: si sube la demanda o baja la oferta, sube el precio."},
    {"texto": "Marketing directo implica acciones orientadas a implicar directamente al cliente potencial.", "respuesta": false,
     "explicacion": ". Ojo, sí es directo, pero no busca implicar, sino obtener una respuesta inmediata (correo, teléfono, etc.)."},
    {"texto": "Nicho de mercado es el porcentaje de participación de una empresa respecto al total de ventas del mercado.", "respuesta": false,
     "explicacion": ". Ojo, eso es cuota de mercado; nicho es un segmento muy concreto y especializado."},
    {"texto": "Para buscar un socio, convencerás si tu idea es brillante y tu trayectoria profesional avala el éxito conjunto.", "respuesta": true,
     "explicacion": ". En etapas iniciales, el socio confía tanto en la persona como en la idea."},
    {"texto": "Para el fabricante, el precio debe cubrir costes y permitir beneficios para seguir produciendo.", "respuesta": true,
     "explicacion": ". Si el precio no cubre costes, la empresa pierde viabilidad."},
    {"texto": "Para el marketing operativo es fundamental conocer las preferencias cambiantes del consumidor.", "respuesta": false,
     "explicacion": ". Ojo, eso pertenece al marketing estratégico; el operativo ejecuta las acciones concretas."},
    {"texto": "Para la segmentación de mercados usamos variables psicográficas como ingresos, profesión, religión y educación.", "respuesta": false,
     "explicacion": ". Ojo, esas son variables demográficas; las psicográficas son estilo de vida, valores y personalidad."},
    {"texto": "Para tener una buena red comercial basta con contratar a los mejores vendedores del mercado.", "respuesta": false,
     "explicacion": ". Ojo, también necesitas formación, estrategia y coherencia con la marca."},
    {"texto": "Peeble fue un ejemplo de crowdfunding (PMV).", "respuesta": false,
     "explicacion": ". Validaron su producto con preventas en Kickstarter antes de producirlo."},
    {"texto": "Pivotar en una startup significa corregir el rumbo con base en aprendizaje validado.", "respuesta": true,
     "explicacion": ". Ojo, no es improvisar: es cambiar dirección basándose en datos reales."},
    {"texto": "Planear la jerarquía de mandos es esencial para diseñar un sistema de organización eficiente.", "respuesta": true,
     "explicacion": ". Define autoridad, comunicación y responsabilidad."},
    {"texto": "Plantearse constantemente por qué y generar cambios deliberados estimula la creatividad sistemática.", "respuesta": true,
     "explicacion": ". Cuestionar lo establecido impulsa innovación estructurada."},
    {"texto": "Proteger una invención con patente otorga derechos exclusivos durante un periodo limitado.", "respuesta": true,
     "explicacion": ". En general, 20 años desde la fecha de solicitud."},
    {"texto": "Quien contrata leasing asume gastos de mantenimiento y tributos.", "respuesta": true,
     "explicacion": ". Ojo, esto lo diferencia del renting, donde la empresa de renting asume esos costes."},
    {"texto": "Recursos humanos y dirección deben coordinar para formar el plan de carrera de un empleado.", "respuesta": true,
     "explicacion": ". Es clave para desarrollar talento interno y retener personal."},
    {"texto": "Reducir costes fijos aumenta automáticamente el margen neto.", "respuesta": false,
     "explicacion": ". Ojo, puede mejorar el margen, pero depende también de ingresos y costes variables."},
    {"texto": "Reunir información de mercado permite validar oportunidades y amenazas.", "respuesta": true,
     "explicacion": ". Es la base del análisis DAFO: identificar factores internos y externos."},
    {"texto": "RSC se refiere a personas, planeta y beneficios (triple P).", "respuesta": true,
     "explicacion": ". Triple enfoque de sostenibilidad económica, social y ambiental."},
    {"texto": "Segmentar mercados ayuda a adaptar productos y estrategias a cada grupo de consumidores.", "respuesta": true,
     "explicacion": ". Evita generalizar y mejora la eficacia del marketing."},
    {"texto": "Según Kotler, el producto incluye elementos tangibles e intangibles.", "respuesta": true,
     "explicacion": ". Incluye imagen, servicio, envase y valor percibido."},
    {"texto": "Según Maslow, la autorrealización es la necesidad más alta.", "respuesta": true,
     "explicacion": ". Es el nivel máximo: desarrollar el potencial personal."},
    {"texto": "Si un producto se vende bien, necesariamente es de alta calidad.", "respuesta": false,
     "explicacion": ". Ojo, el éxito de ventas puede deberse al marketing, no a la calidad real."},
    {"texto": "Si una empresa no tiene clientes, debe pivotar o cambiar su propuesta de valor.", "respuesta": true,
     "explicacion": ". Es señal de que el modelo actual no encaja con el mercado."},
    {"texto": "Solo el área de marketing debe preocuparse por la satisfacción del cliente.", "respuesta": false,
     "explicacion": ". Ojo, todos los departamentos influyen en la experiencia del cliente."},
    {"texto": "Toda innovación requiere gran inversión económica.", "respuesta": false,
     "explicacion": ". Ojo, también existen innovaciones de proceso o gestión con bajo coste."},
    {"texto": "Todo proyecto emprendedor debe validar si hay mercado antes de invertir mucho dinero.", "respuesta": true,
     "explicacion": ". Es la esencia del enfoque Lean Startup."},
    {"texto": "Tropicfeel es un caso exitoso de crowdfunding para validar mercado.", "respuesta": true,
     "explicacion": ". Financiaron su producto validando interés antes de fabricarlo."},
    {"texto": "Un bien de conveniencia se compra con frecuencia y poca planificación.", "respuesta": true,
     "explicacion": ". Son compras rutinarias, como pan, leche o pilas."},
    {"texto": "Un crowdfunding ofrece participación accionarial a cambio de capital.", "respuesta": false,
     "explicacion": ". Ojo, eso sería equity crowdfunding; el clásico ofrece recompensas, no acciones."},
    {"texto": "Un líder autoritario promueve autonomía y trabajo en equipo.", "respuesta": false,
     "explicacion": ". Es centralizador y toma decisiones sin consultar."},
    {"texto": "Un modelo CANVAS incluye propuesta de valor, recursos clave y flujos de ingresos.", "respuesta": true,
     "explicacion": ". Son tres de los nueve bloques del modelo."},
    {"texto": "Una empresa sostenible aplica economía circular y responsabilidad social.", "respuesta": true,
     "explicacion": ". Ojo, la sostenibilidad combina ecología, ética y rentabilidad."},
    {"texto": "Una innovación disruptiva cambia radicalmente la forma de ofrecer valor.", "respuesta": true,
     "explicacion": ". Ejemplo: Netflix sustituyendo el videoclub tradicional."},
    {"texto": "Una startup busca validar hipótesis de negocio con el menor coste posible.", "respuesta": true,
     "explicacion": ". Ojo, esa es la filosofía de Lean Startup: aprender rápido y barato."},
    {"texto": "Venture Capital invierte en fases tempranas de startups sin modelo validado.", "respuesta": false,
     "explicacion": ". Ojo, eso lo hacen business angels; el Venture Capital entra cuando ya hay validación inicial."},
    {"texto": "Zappos validó su modelo mediante un PMV tipo Mago de Oz.", "respuesta": true,
     "explicacion": ". Vendían zapatos online y los compraban manualmente tras cada pedido para validar el concepto."},
    {"texto": "Una sociedad solo se puede fundar cuando los socios tienen la misma implicación en horas de trabajo.", "respuesta": false,
     "explicacion": ". Ojo, puede haber socios inversores y socios trabajadores; no hace falta igualdad de horas."},
    {"texto": "Una spin-off es una empresa que nace separándose de otra mayor y adquiere autonomía propia.", "respuesta": true,
     "explicacion": ". Muy comunes en universidades o grandes corporaciones."},
    {"texto": "Una startup es una organización provisional cuyo objetivo es validar un modelo de negocio viable, replicable y escalable.", "respuesta": true,
     "explicacion": ". Es la definición más aceptada por Eric Ries."},
    {"texto": "Una startup combina desarrollo de producto, validación y crecimiento al mismo tiempo.", "respuesta": true,
     "explicacion": ". Es un proceso simultáneo, no lineal."},
    {"texto": "Un modelo de negocio rentable es aquel que genera beneficios recurrentes con costes controlados.", "respuesta": true,
     "explicacion": ". Ojo, no basta con beneficios puntuales; debe ser sostenible en el tiempo."},
    {"texto": "Un monopolio ocurre cuando existen varios oferentes y un solo comprador.", "respuesta": false,
     "explicacion": ". Ojo, eso es monopsonio; el monopolio es un solo oferente y muchos compradores."},
    {"texto": "Un monopsonio limitado se da cuando hay pocos oferentes y un único comprador.", "respuesta": true,
     "explicacion": ". Ejemplo: grandes supermercados frente a pequeños productores."},
    {"texto": "Un paraguas se considera un bien de compra habitual o de conveniencia.", "respuesta": true,
     "explicacion": ". Es una compra rápida, de bajo coste y poca implicación."},
    {"texto": "Un PowerPoint o un vídeo pueden servir como producto mínimo viable para validar una idea.", "respuesta": true,
     "explicacion": ". Ojo, basta con que comunique la propuesta y se pueda medir el interés."},
    {"texto": "Un socio es aquella persona que aporta al proyecto algo que éste necesita, sea capital o conocimiento.", "respuesta": true,
     "explicacion": ". Se valora tanto la aportación económica como la estratégica o técnica."},
    {"texto": "Una categoría de productos agrupa artículos que satisfacen la misma necesidad del consumidor.", "respuesta": true,
     "explicacion": ". Ojo, las categorías permiten analizar competencia directa."},
    {"texto": "Una organización formal define las relaciones jerárquicas establecidas por la dirección.", "respuesta": true,
     "explicacion": ". Contrasta con la organización informal, basada en relaciones personales."},
    {"texto": "Una organización informal surge espontáneamente entre los trabajadores sin estar definida por la dirección.", "respuesta": true,
     "explicacion": ". Ojo, son redes de comunicación o apoyo no oficiales pero muy influyentes en la empresa."},
    {"texto": "Una patente otorga un derecho exclusivo de explotación por un tiempo limitado.", "respuesta": true,
     "explicacion": ". En general, 20 años desde la fecha de solicitud si se pagan las tasas."},
    {"texto": "Una startup debe dejar de pivotar cuando dispone de pedidos reiterativos y modelo económico validado.", "respuesta": true,
     "explicacion": ". Si ya hay clientes y ventas constantes, el modelo está validado y toca escalar."},
    {"texto": "Una empresa puede ser sostenible sin aplicar responsabilidad social corporativa.", "respuesta": false,
     "explicacion": ". Ojo, la sostenibilidad incluye la RSC; sin ella, solo habría equilibrio financiero."},
    {"texto": "Una empresa puede considerar que Beneficio = Ingreso − Gasto.", "respuesta": true,
     "explicacion": ". Es la fórmula básica del resultado económico, aunque simplificada."},
    {"texto": "Una empresa sin clientes aún no tiene negocio validado.", "respuesta": true,
     "explicacion": ". Ojo, hasta que no hay ventas reales, no hay validación de mercado."},
    {"texto": "Una oportunidad de mercado se da cuando existen necesidades no satisfechas por el mercado actual.", "respuesta": true,
     "explicacion": ". Es la base para crear productos nuevos o diferenciarse."},
    {"texto": "Una organización lineal se basa en el principio de mando único.", "respuesta": true,
     "explicacion": ". Cada empleado responde a un solo jefe, lo que simplifica jerarquía."},
    {"texto": "Una patente registrada en Suiza otorga protección mundial automáticamente.", "respuesta": false,
     "explicacion": ". Ojo, las patentes son territoriales; se necesita solicitar protección internacional aparte."},
    {"texto": "Una política de precios diferenciada puede segmentar por capacidad económica o sensibilidad al precio.", "respuesta": true,
     "explicacion": ". Ojo, se usa mucho en sectores como transporte o turismo."},
    {"texto": "Una RSC efectiva integra la triple cuenta de resultados: personas, planeta y beneficios.", "respuesta": true,
     "explicacion": ". Mide sostenibilidad en los tres ejes clave (social, ambiental y económico)."},
    {"texto": "Una startup funciona como una empresa convencional desde el inicio.", "respuesta": false,
     "explicacion": ". Ojo, una startup busca validar su modelo; la convencional ya lo tiene consolidado."},
    {"texto": "Una subvención a empleados para cursos no relacionados con el trabajo es salario emocional.", "respuesta": false,
     "explicacion": ". Ojo, el salario emocional debe aportar valor al desarrollo personal o profesional real."},
    {"texto": "Una venta personal busca cultivar relaciones y buena imagen corporativa.", "respuesta": false,
     "explicacion": ". Ojo, la venta personal busca cerrar ventas directas; cultivar relaciones es marketing relacional."},
    {"texto": "Un bien de consumo duradero es aquel que no se destruye con su uso.", "respuesta": true,
     "explicacion": ". Ejemplo: coche, lavadora o televisor; duran varios ciclos de uso."},
    {"texto": "Un cliente insatisfecho siempre comunica su queja a la empresa.", "respuesta": false,
     "explicacion": ". Ojo, la mayoría no se quejan: simplemente cambian de proveedor."},
    {"texto": "Un mercado monopolista se caracteriza por un solo oferente y muchos demandantes.", "respuesta": true,
     "explicacion": ". Es el caso de monopolios naturales o controlados."},
    {"texto": "Un mercado oligopolista tiene pocos oferentes que controlan gran parte del mercado.", "respuesta": true,
     "explicacion": ". Ejemplo: aerolíneas o compañías telefónicas."},
    {"texto": "Un modelo Canvas fue creado por Alexander Osterwalder.", "respuesta": true,
     "explicacion": ". Ojo, no confundir con Eric Ries, creador de Lean Startup."},
    {"texto": "Un plan de acogida ayuda a mejorar la adaptación y retención del talento.", "respuesta": true,
     "explicacion": ". Facilita integración, motivación y productividad del nuevo empleado."},
    {"texto": "Un plan de marketing operativo define las acciones tácticas para alcanzar los objetivos estratégicos.", "respuesta": true,
     "explicacion": ". Ojo, el estratégico marca el rumbo y el operativo ejecuta las acciones."},
    {"texto": "Un PMV busca validar hipótesis clave del modelo de negocio.", "respuesta": true,
     "explicacion": ". Es la herramienta principal para aprender del mercado real."},
    {"texto": "Un precio justo refleja tanto el coste de producción como el valor percibido por el cliente.", "respuesta": true,
     "explicacion": ". Ojo, el valor percibido puede ser subjetivo pero determina disposición a pagar."},
    {"texto": "Un producto de conveniencia requiere gran implicación del consumidor antes de la compra.", "respuesta": false,
     "explicacion": ". Ojo, los de conveniencia se compran rápido, sin análisis ni comparación."},
    {"texto": "Un prototipo permite simular el funcionamiento real del producto en manos del usuario.", "respuesta": true,
     "explicacion": ". Sirve para testear usabilidad y detectar errores tempranos."},
    {"texto": "Un socio inversor aporta únicamente capital sin participar en la gestión del negocio.", "respuesta": true,
     "explicacion": ". Ojo, se diferencia del socio industrial, que sí aporta trabajo o conocimiento."},
    {"texto": "Un socio industrial aporta recursos, conocimiento o tecnología además de capital.", "respuesta": true,
     "explicacion": ". Es clave en proyectos tecnológicos o especializados."},
    {"texto": "Un trabajador motivado es más productivo y mejora el clima laboral.", "respuesta": true,
     "explicacion": ". Ojo, la motivación influye directamente en la eficiencia y compromiso."},
    {"texto": "Una ventaja competitiva debe ser sostenible y difícil de imitar.", "respuesta": true,
     "explicacion": ". Ejemplo: marca, innovación o servicio al cliente único."},
    {"texto": "Una venta relacional busca construir relaciones duraderas más allá de la transacción inmediata.", "respuesta": true,
     "explicacion": ". Ojo, fidelizar es más rentable que captar nuevos clientes."},
    {"texto": "Los costes variables son aquellos que no cambian con el volumen de producción.", "respuesta": false,
     "explicacion": ". Ojo, los variables cambian proporcionalmente al nivel de producción."},
    {"texto": "El punto muerto indica el nivel de ventas necesario para cubrir todos los costes.", "respuesta": true,
     "explicacion": ". También se llama umbral de rentabilidad o break-even point."},
    {"texto": "El margen bruto es la diferencia entre las ventas y los costes variables.", "respuesta": true,
     "explicacion": ". Indica cuánto margen queda para cubrir costes fijos y generar beneficio."},
    {"texto": "El margen neto se obtiene restando todos los gastos a los ingresos totales.", "respuesta": true,
     "explicacion": ". Es el beneficio final después de impuestos y gastos financieros."},
    {"texto": "El flujo de caja positivo indica que la empresa genera más dinero del que gasta.", "respuesta": true,
     "explicacion": ". Ojo, flujo positivo implica liquidez, no necesariamente beneficio contable."},
    {"texto": "El análisis DAFO estudia Debilidades, Amenazas, Fortalezas y Oportunidades.", "respuesta": true,
     "explicacion": ". Es una herramienta estratégica básica de diagnóstico interno y externo."},
    {"texto": "El análisis PESTEL analiza factores políticos, económicos, sociales, tecnológicos, ecológicos y legales.", "respuesta": true,
     "explicacion": ". Ojo, sirve para analizar el entorno macroeconómico."},
    {"texto": "El Business Model Canvas incluye nueve bloques principales.", "respuesta": true,
     "explicacion": ". Describe cómo se crea, entrega y captura valor en una empresa."},
    {"texto": "El marketing mix está formado por las 4 P: producto, precio, plaza y promoción.", "respuesta": true,
     "explicacion": ". Son las herramientas tácticas del marketing operativo."},
    {"texto": "El benchmarking consiste en copiar exactamente las prácticas de la competencia.", "respuesta": false,
     "explicacion": ". Ojo, se trata de aprender y adaptar, no copiar ciegamente."},
    {"texto": "El feedback del cliente es fundamental en metodologías ágiles y Lean Startup.", "respuesta": true,
     "explicacion": ". El aprendizaje validado depende del feedback real de usuarios."},
    {"texto": "El capital riesgo (Venture Capital) invierte en empresas consolidadas sin riesgo.", "respuesta": false,
     "explicacion": ". Ojo, el Venture Capital invierte precisamente en alto riesgo con gran potencial de retorno."},
    {"texto": "El crowdfunding consiste en financiar proyectos mediante pequeñas aportaciones de muchas personas.", "respuesta": true,
     "explicacion": ". Es financiación colectiva a través de plataformas digitales."},
    {"texto": "El crowdlending implica préstamos colectivos a cambio de intereses, no recompensas.", "respuesta": true,
     "explicacion": ". Ojo, es financiación participativa con retorno financiero, no simbólico."},
    {"texto": "El factor humano es clave en la gestión empresarial moderna.", "respuesta": true,
     "explicacion": ". Las personas son el recurso diferencial de la empresa actual."},
    {"texto": "El liderazgo transformacional motiva e inspira a los empleados para alcanzar metas comunes.", "respuesta": true,
     "explicacion": ". Ojo, fomenta crecimiento personal y compromiso con la visión."},
    {"texto": "El liderazgo transaccional se basa en recompensas y castigos.", "respuesta": true,
     "explicacion": ". Es un estilo de control basado en incentivos y cumplimiento de normas."},
    {"texto": "El liderazgo liberal se caracteriza por la falta total de control y orientación.", "respuesta": false,
     "explicacion": ". Ojo, aunque delega, el líder liberal mantiene cierta supervisión mínima."},
    {"texto": "El liderazgo situacional adapta el estilo a las circunstancias y madurez del equipo.", "respuesta": true,
     "explicacion": ". El líder elige su estilo según el contexto, no de forma fija."},
    {"texto": "El marketing social busca promover cambios de comportamiento beneficiosos para la sociedad.", "respuesta": true,
     "explicacion": ". Ejemplo: campañas de salud, reciclaje o seguridad vial."},
    {"texto": "El marketing relacional pretende fidelizar al cliente a largo plazo.", "respuesta": true,
     "explicacion": ". Ojo, no se centra solo en la venta, sino en mantener la relación y confianza del cliente."},
    {"texto": "El marketing estratégico analiza las necesidades del consumidor y define estrategias a medio-largo plazo.", "respuesta": true,
     "explicacion": ". Es la parte de planificación y estudio de mercado antes de ejecutar acciones."},
    {"texto": "El marketing operativo ejecuta las estrategias definidas por el marketing estratégico.", "respuesta": true,
     "explicacion": ". Ojo, el operativo convierte las estrategias en acciones concretas (publicidad, precios...)."},
    {"texto": "El neuromarketing estudia las reacciones cerebrales ante estímulos publicitarios.", "respuesta": true,
     "explicacion": ". Usa técnicas como resonancia o eye-tracking para medir emociones y atención."},
    {"texto": "El plan de empresa define objetivos, estrategias, recursos y viabilidad del negocio.", "respuesta": true,
     "explicacion": ". Ojo, es el documento base para presentar un proyecto a socios o inversores."},
    {"texto": "El punto muerto financiero se alcanza cuando la empresa cubre sus gastos operativos y financieros.", "respuesta": true,
     "explicacion": ". Es el equilibrio total entre ingresos y todos los costes, incluidos los financieros."},
    {"texto": "El valor percibido es la diferencia entre los beneficios que el cliente percibe y el coste que asume.", "respuesta": true,
     "explicacion": ". Ojo, la clave es la percepción del cliente, no el valor objetivo."},
    {"texto": "El valor de marca (branding) se refiere únicamente al logotipo de la empresa.", "respuesta": false,
     "explicacion": ". Ojo, el branding incluye reputación, emociones, confianza y coherencia visual."},
    {"texto": "El producto mínimo viable se usa para aprender del cliente con el menor esfuerzo posible.", "respuesta": true,
     "explicacion": ". Es el núcleo de la metodología Lean Startup: probar, medir y aprender."},
    {"texto": "El proceso de innovación incluye fases de ideación, desarrollo y comercialización.", "respuesta": true,
     "explicacion": ". Son las tres etapas clásicas para transformar una idea en producto."},
    {"texto": "El DAFO es una herramienta estática que no se actualiza nunca.", "respuesta": false,
     "explicacion": ". Ojo, el DAFO debe actualizarse cada vez que cambian las condiciones del entorno."},
    {"texto": "El crecimiento sostenible combina rentabilidad, responsabilidad y respeto ambiental.", "respuesta": true,
     "explicacion": ". Es el enfoque moderno de equilibrio económico, social y ecológico."},
    {"texto": "El emprendimiento implica asumir riesgos para aprovechar oportunidades de mercado.", "respuesta": true,
     "explicacion": ". Ojo, el riesgo controlado es parte esencial del emprendimiento."},
    {"texto": "El modelo Lean Startup busca crear empresas eficientes a través de la experimentación rápida.", "respuesta": true,
     "explicacion": ". Se basa en probar hipótesis, medir resultados y aprender antes de invertir más."},
    {"texto": "El prototipado rápido permite testear ideas sin desarrollar el producto completo.", "respuesta": true,
     "explicacion": ". Ahorra tiempo y recursos en validación temprana."},
    {"texto": "El trabajo en equipo mejora la creatividad y la resolución de problemas.", "respuesta": true,
     "explicacion": ". Ojo, la diversidad de ideas en grupo potencia soluciones más completas."},
    {"texto": "El liderazgo autoritario fomenta la participación activa del equipo.", "respuesta": false,
     "explicacion": ". Ojo, el líder autoritario impone decisiones y limita la participación."},
    {"texto": "El empowerment otorga autonomía y responsabilidad a los empleados.", "respuesta": true,
     "explicacion": ". Empoderar aumenta la motivación y la innovación."},
    {"texto": "El benchmarking interno compara áreas dentro de la misma organización.", "respuesta": true,
     "explicacion": ". Sirve para detectar buenas prácticas internas y replicarlas."},
    {"texto": "El análisis del mercado es irrelevante en las startups tecnológicas.", "respuesta": false,
     "explicacion": ". Ojo, incluso con tecnología disruptiva, hay que entender el mercado y sus usuarios."},
    {"texto": "El plan financiero debe prever ingresos, gastos, inversiones y flujos de caja.", "respuesta": true,
     "explicacion": ". Ojo, es esencial para evaluar la viabilidad del negocio."},
    {"texto": "El control de gestión permite medir el desempeño y corregir desviaciones.", "respuesta": true,
     "explicacion": ". Es el sistema que asegura que se cumplan los objetivos estratégicos."},
    {"texto": "El análisis de la competencia sirve para identificar ventajas diferenciales.", "respuesta": true,
     "explicacion": ". Permite definir qué te hace único frente a otros."},
    {"texto": "El marketing digital no permite medir los resultados en tiempo real.", "respuesta": false,
     "explicacion": ". Ojo, es justo lo contrario: su gran ventaja es la medición inmediata."},
    {"texto": "El propósito de una empresa sostenible es generar valor económico, social y ambiental.", "respuesta": true,
     "explicacion": ". Es el llamado triple balance de sostenibilidad."},
    {"texto": "El modelo Canvas fue diseñado por Eric Ries.", "respuesta": false,
     "explicacion": ". Ojo, lo diseñó Alexander Osterwalder; Eric Ries creó Lean Startup."},
    {"texto": "El bootstrapping significa financiarse con recursos propios.", "respuesta": true,
     "explicacion": ". Ojo, implica empezar sin inversión externa y con mucho control de gasto."},
    {"texto": "El business plan incluye resumen ejecutivo, plan financiero y plan de marketing.", "respuesta": true,
     "explicacion": ". Es el documento base para presentar una empresa a socios o bancos."},
    {"texto": "El feedback negativo de los clientes siempre es perjudicial.", "respuesta": false,
     "explicacion": ". Ojo, el feedback negativo es el más útil para mejorar productos o servicios."},
    {"texto": "El liderazgo efectivo requiere comunicación, empatía y visión compartida.", "respuesta": true,
     "explicacion": ". Es la combinación perfecta para motivar y coordinar equipos."},
    {"texto": "El análisis de costes ayuda a determinar el precio mínimo rentable.", "respuesta": true,
     "explicacion": ". Permite saber el punto donde los ingresos cubren todos los gastos."},
    {"texto": "El liderazgo transformacional promueve castigos y control rígido para mantener el orden.", "respuesta": false,
     "explicacion": ". Ojo, eso es liderazgo transaccional; el transformacional inspira y guía."},
    {"texto": "El análisis financiero permite medir la rentabilidad y liquidez de una empresa.", "respuesta": true,
     "explicacion": ". Evalúa la salud económica mediante ratios y balances."},
    {"texto": "La innovación disruptiva mejora ligeramente un producto existente.", "respuesta": false,
     "explicacion": ". Ojo, eso sería innovación incremental; la disruptiva cambia completamente el mercado."},
    {"texto": "El análisis PESTEL sirve para estudiar los factores internos de la empresa.", "respuesta": false,
     "explicacion": ". Ojo, el PESTEL analiza factores externos: políticos, sociales, legales, etc."},
    {"texto": "El análisis DAFO combina factores internos (D y F) con factores externos (A y O).", "respuesta": true,
     "explicacion": ". Es el cruce entre diagnóstico interno y entorno."},
    {"texto": "El plan estratégico define las acciones concretas de corto plazo.", "respuesta": false,
     "explicacion": ". Ojo, el estratégico marca objetivos generales a medio y largo plazo."},
    {"texto": "El plan operativo convierte la estrategia en tareas y objetivos específicos.", "respuesta": true,
     "explicacion": ". Es la traducción práctica de la estrategia general."},
    {"texto": "El DAFO solo sirve para empresas nuevas.", "respuesta": false,
     "explicacion": ". Ojo, cualquier empresa lo puede usar para reevaluar su posición en el mercado."},
    {"texto": "El marketing mix incluye la variable 'personas' en las 4P originales.", "respuesta": false,
     "explicacion": ". Ojo, personas se añade más tarde como la quinta P en servicios."},
    {"texto": "El análisis de competencia ayuda a definir posicionamiento y estrategia de diferenciación.", "respuesta": true,
     "explicacion": ". Ojo, conocer competidores evita estrategias ciegas o ineficaces."},
    {"texto": "El plan financiero muestra la situación patrimonial en un momento concreto.", "respuesta": false,
     "explicacion": ". Ojo, eso lo hace el balance; el plan financiero proyecta ingresos y gastos futuros."},
    {"texto": "El marketing interno busca motivar al personal para mejorar la atención al cliente.", "respuesta": true,
     "explicacion": ". Ojo, empleados motivados transmiten mejor la cultura de marca."},
    {"texto": "El plan de comunicación interna tiene como objetivo principal evitar rumores.", "respuesta": false,
     "explicacion": ". Ojo, su fin es mejorar la transparencia y alineación, no solo evitar rumores."},
    {"texto": "El valor añadido es la diferencia entre el valor de venta y el coste de producción.", "respuesta": true,
     "explicacion": ". Mide cuánto valor genera una empresa sobre los insumos usados."},
    {"texto": "El control presupuestario permite comparar lo real con lo planificado.", "respuesta": true,
     "explicacion": ". Ojo, es clave para detectar desviaciones y corregir a tiempo."},
    {"texto": "El marketing social solo lo aplican ONGs.", "respuesta": false,
     "explicacion": ". Ojo, también lo aplican empresas con campañas de responsabilidad o concienciación."},
    {"texto": "La ética empresarial consiste en aplicar valores morales en la toma de decisiones corporativas.", "respuesta": true,
     "explicacion": ". Es actuar con coherencia entre beneficio y responsabilidad."},
    {"texto": "El liderazgo democrático fomenta la participación y la comunicación bidireccional.", "respuesta": true,
     "explicacion": ". Es el estilo más colaborativo y motivador."},
    {"texto": "El plan de marketing define cómo alcanzar los objetivos comerciales y de comunicación.", "respuesta": true,
     "explicacion": ". Es el documento que concreta la estrategia para vender y posicionar."},
    {"texto": "El análisis financiero solo se hace al final del ejercicio contable.", "respuesta": false,
     "explicacion": ". Ojo, debe hacerse de forma continua para ajustar decisiones durante el año."},
    {"texto": "El análisis de riesgos identifica amenazas y su impacto potencial en la empresa.", "respuesta": true,
     "explicacion": ". Ojo, permite anticipar problemas y preparar planes de contingencia."},
    {"texto": "La rentabilidad económica mide el beneficio neto respecto a las ventas.", "respuesta": false,
     "explicacion": ". Ojo, eso sería rentabilidad sobre ventas; la económica se calcula sobre el activo total."},
    {"texto": "El ROI mide el rendimiento de una inversión.", "respuesta": true,
     "explicacion": ". Se calcula como beneficio neto dividido por inversión total."},
    {"texto": "El liderazgo carismático se basa en la autoridad formal del cargo.", "respuesta": false,
     "explicacion": ". Ojo, se basa en el magnetismo personal, no en el puesto."},
    {"texto": "El marketing emocional busca conectar con el consumidor a través de sentimientos y experiencias.", "respuesta": true,
     "explicacion": ". Ojo, apela a la emoción más que a la lógica para generar vínculo de marca."}
];

// --- FRASES DE ÁNIMO ---
const frases_animo = [
  "¡Muy bien amor! 😎",
  "¡Eso es, perfecto, te camelo caramelo! 🔥",
  "¡Ole tú huevos! 💪",
  "¡Exacto, estás on fire tia! 🚀",
  "¡Muy bien pensado tronca! 🧠",
  "¡Qué máquina eres! 😍",
  "¡Correcto, así se hace! 👏",
  "¡Te lo sabes de memoria ya! 💥"
];

let i = 0;
let puntuacion = 0;

// --- FUNCIONES ---
function mostrarMensaje(texto, tipo) {
  const chat = document.getElementById("chat");
  const msg = document.createElement("div");
  msg.classList.add("message", tipo);
  msg.textContent = texto;
  chat.appendChild(msg);
  chat.scrollTo({ top: chat.scrollHeight, behavior: "smooth" });
}

function responder(respuestaUsuario) {
  if (!preguntas[i]) return;

  mostrarMensaje(respuestaUsuario ? "✔️ Verdadero" : "❌ Falso", "user");

  if (respuestaUsuario === preguntas[i].respuesta) {
    puntuacion++;
    mostrarMensaje(frases_animo[Math.floor(Math.random() * frases_animo.length)], "bot");
  } else {
    mostrarMensaje("❌ Incorrecto. " + preguntas[i].explicacion, "bot");
  }

  i++;
  if (i < preguntas.length) {
    setTimeout(() => {
      mostrarMensaje(preguntas[i].texto, "bot");
    }, 700);
  } else {
    setTimeout(() => {
      mostrarMensaje(`🏁 Has acertado ${puntuacion} de ${preguntas.length} preguntas. 💡 ¡Sigue practicando, que vas de lujo!`, "bot");
      document.getElementById("btnV").disabled = true;
      document.getElementById("btnF").disabled = true;
    }, 800);
  }
}

// --- FUNCIÓN PARA MEZCLAR ---
function mezclarPreguntas(array) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
  return array;
}

// --- ARRANQUE SEGURO ---
document.addEventListener("DOMContentLoaded", () => {
  mezclarPreguntas(preguntas);
  i = 0;
  puntuacion = 0;

  mostrarMensaje("🧠 Bienvenido a tu test de Verdadero/Falso. ¡Pulsa V o F para empezar! 💬", "bot");
  setTimeout(() => {
    mostrarMensaje(preguntas[i].texto, "bot");
  }, 500);

  document.getElementById("btnV").onclick = () => responder(true);
  document.getElementById("btnF").onclick = () => responder(false);
});


